# Mostly taken from the Kodeco (Formerly Ray Wenderlich) Swift style guide. Minor modifications done to align with my personal preferences

excluded:
  - .build
  - .github
  - .vscode
  - HackerNewsApp.xcodeproj
  - ${PWD}/Carthage
  - ${PWD}/Pods
  - ${PWD}/DerivedData
  - MarkdownifyHTML/.build
  - MarkdownifyHTML/.swiftpm


disabled_rules:
  - trailing_comma
  - todo
  - type_name
  - mark

analyzer_rules:
  - unused_import

opt_in_rules:
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - collection_alignment
  - colon
  - comma
  - comment_spacing
  - compiler_protocol_init
  - computed_accessors_order
  - convenience_type
  - control_statement
  - custom_rules
  - deployment_target
  - discouraged_direct_init
  - duplicate_imports
  - dynamic_inline
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - explicit_init
  - file_name_no_space
  - file_length
  - function_body_length
  - force_cast
  - force_try
  - is_disjoint
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_nsgeometry_functions
  - legacy_random
  - literal_expression_end_indentation
  - line_length
  - mark
  - modifier_order
  - no_fallthrough_only
  - no_space_in_method_call
  - nsobject_prefer_isequal
  - opening_brace
  - operator_usage_whitespace
  - optional_enum_case_matching
  - prefer_zero_over_explicit_init
  - private_over_fileprivate
  - private_unit_test
  - protocol_property_accessors_order
  - redundant_discardable_let
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_void_return
  - return_arrow_whitespace
  - shorthand_optional_binding
  - sorted_imports
  - statement_position
  - superfluous_disable_command
  - syntactic_sugar
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - unneeded_break_in_switch
  - unowned_variable_capture
  - unused_control_flow_label
  - vertical_whitespace
  - vertical_whitespace_closing_braces
  - void_return
  - force_unwrapping
  - implicitly_unwrapped_optional
  - attributes

attributes:
  always_on_same_line:
    - "@IBSegueAction"
    - "@IBAction"
    - "@NSManaged"
    - "@objc"
    - "@Environment"
    - "@Attribute"
    - "@Relationship"
    - "@UIApplicationDelegateAdaptor"
    - "@Query"

force_cast: warning
force_try: warning
force_unwrapping: error

line_length:
  warning: 120
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1200
function_body_length:
    warning: 60

legacy_hashing: error

identifier_name:
  excluded:
    - i
    - id
    - x
    - y
    - z
    - vc

private_over_fileprivate:
  validate_extensions: true

trailing_whitespace:
  ignores_empty_lines: false
  ignores_comments: true

vertical_whitespace:
  max_empty_lines: 2
