# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

update_fastlane

default_platform(:ios)

desc "Run SwiftLint"
lane :lint do
  setup_ci if ENV['CI']
  increment_build_number
  # increment_version_number(bump_type: 'patch')
  increment_version_number_in_xcodeproj(bump_type: 'patch')
  swiftlint(
    mode: :lint,
    raise_if_swiftlint_error: true,
    reporter: "emoji"
  )
end

desc "Submit current changes"
lane :submit do
  swiftlint(
    mode: :lint,
    raise_if_swiftlint_error: true,
    strict: false,
    reporter: "emoji"
  )
  git_add
  message = prompt(text: "Commit message: ")
  git_commit(path: ["*"], message: message)
end

desc "Push a new beta build to TestFlight"
lane :beta do
  setup_ci if ENV['CI']
  lint
  increment_version_number_in_xcodeproj(bump_type: 'minor')
  add_badge
  build_app(scheme: "Hermes")

  changelog_from_git_commits(merge_commit_filtering: 'exclude_merges')
  upload_to_testflight
end
