# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

update_fastlane

default_platform(:ios)

desc "Run SwiftLint"
lane :lint do
  increment_version_number_in_xcodeproj(bump_type: 'patch')
  swiftlint(
    mode: :lint,
    raise_if_swiftlint_error: true,
    reporter: "emoji"
  )
end

desc "Push a new beta build to TestFlight"
lane :beta do
  increment_build_number_in_xcodeproj
  increment_version_number_in_xcodeproj(bump_type: 'major')
  add_badge
  build_app(scheme: "Hermes")

  changelog_from_git_commits(merge_commit_filtering: 'exclude_merges')
  upload_to_testflight
end
